### ISSUE TITLE
MDB RX Pullup falsch

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/kassenautomat.mdb-interface#10]
Die Widerstände an MDB_MR, die nach GND gehen, müssen nach VCC. D.h. R3 R4 D1 spiegeln. D1 dann richtigrum.

**Comment by patkan** [comment]
Hi @mgmax meintest du mit "D1 dann richtigrum", dass D1 von VCC nach Busleitung zeigen soll? Ich nehme mal an ja...

**Comment by mgmax** [comment]
Ja. MDB_MR ist an der Gegenstelle ein open collector Ausgang, ich hab 
das grad nochmal in der Spec nachgeschaut.

**Comment by mgmax** [comment]
passt so, Danke!
